openoakland/openousd-site

- src/pages/index.js
small fix to make React/Gatsby happy
> fixed className

- src/components/header.js
- src/components/header.scss
Accessibility problem and making bar full width
> Responsive nav

- src/components/footer.js
- src/components/footer.scss
- src/components/layout.js
Got with the program and implemented SCSS, as well as fixing the problem of footer not sticking to bottom.  Also made part of the text <strong> like in the design mockup.  File structure now matches the header's, so other people can follow our layout.
> footer is sticky, only bold in part like design doc

- src/components/departments-table.js
- src/components/footer.js
- src/components/header.js
- src/components/header.scss
Fixed a few small things that WAVE informed us about.  See commit history for details
> Wave fixes

- src/components/footer.js
- src/pages/about-data.js
- src/pages/contact.js
- src/styles/pages/contact.scss
Page to share links to data source code for OpenOUSD. Goal is to build trust with visitors with transparency.
Links to it in the footer and contact page.
> Data & Code Source Page

- data/central-programs.json
- data/sankey-restricted.json
- data/sankey.json
> updating data with fixed category names

- package-lock.json
- package.json
- src/components/central-program.js
- src/components/central-program/central-program.scss
- src/components/layout.js
- src/components/scroll-widget.js
- src/components/scroll-widget.scss
- src/pages/central-programs.js
- src/styles/style.scss
PR is bigger than it looks, lots of the lines changed are from Prettier formatting existing code :) 
---
> Scroller widget

- .gitignore
- src/pages/about-data.js
This PR is now complete! Thanks for your help, @jbaldo !
> Power `AboutData` page with Contentful

- src/components/categories-table.js
- src/pages/about-categories.js
All the Contentful stuff was in for this PR, so we should be good on translations :) However, this PR clearly does not translate the names of the programs (open question on my end if/how we should do that).
**Before**
**After**
> Contentful about categories page

- package.json
- src/components/new-feature.js
- src/pages/whats-new.js
- src/styles/pages/whats-new.scss
> Use contenful to show whats-new page with assets

- gatsby-node.js
- src/components/central-programs-table.js
- src/pages/central-programs.js
> create links for each program in the table

- data/central-programs-resources.json
- data/central-programs-sankey.json
- data/sankey-restricted.json
- data/sankey.json
- scripts/build_json.py
Manually spot checked a bunch of the data. I think it's all the same, but some of it is being returned in a different order. Hopefully after this commit, a change will actually signify a change in the data.
Independent companion to: https://github.com/openoakland/openousd-api/pull/10
> pull data from local db, should be the same but different order

- src/components/central-program.js
- src/components/central-program/program-data-overview-table.js
- src/components/table-utilities.js
Example:
Also sidenote, Prettier reformatted a bunch of stuff I didn't touch, I can highlight the code that actually did change in this PR.
> Show deltas for FTEs & total positions in central program pages

- src/components/central-programs-table.js
- src/pages/central-programs.js
Not sorted when locale is not on default (en).
> changes to add locale in central programs

- src/components/central-program.js
- src/components/central-program/program-data-overview-table.js
Details: https://trello.com/c/gkbNAZ95/65-display-change-from-the-previous-year-on-program-details-page
> Display $$ change from the previous year on program details page

- data/central-programs.json
- package.json
- src/components/central-program.js
- src/components/central-program/program-data-overview-table.js
- src/components/central-program/staff-labor-unions-chart.js
- src/components/central-program/staff-labor-unions-table.js
- src/components/central-program/staff-roles-table.js
- src/components/central-programs-table.js
- src/components/table-utilities.js
- src/utilities/content-utilities.js
Translations for the program details page. Rebased with Kabirdas's work.
> Translate program details

- src/pages/about-categories.js
- src/pages/central-programs.js
- src/utilities/content-utilities.js
@kbrdsk's work from #55. Just had to rebase to avoid conflicts since I squashed and merged the other branch.
> Translate Central Program Categories On Overview Page

- src/components/central-program.js
- src/components/sankey-chart.js
- src/pages/central-programs.js
Was planning to uncomment the chart and show it, but after reviewing the results for several programs, I don't think it's worth adding it with the data as it is now. Some of the object codes are confusing or the chart isn't too helpful.
Leaving it commented out, but would still like to commit and merge the improvements.
> Program sankey update

- src/pages/about-categories.js
- src/pages/central-programs.js
- src/utilities/content-utilities.js
It looks like we can define localizeCategory as a custom React hook that takes advantage of the useStaticQuery hook from gatsby.
> Use custom hook and static query for category localization

- package-lock.json
- src/components/central-program.js
Display a link to the OUSD website when one is available.
> Ousd program links

- src/components/central-program/staff-roles-table.js
- src/components/central-programs-table.js
- src/components/table-utilities.js
I found that the staff roles table broke because there was no total label, so I added that but now the total row isn't styled correctly. :( I think because the column isn't called `name`. I think it's `row.role_description` in this table.
Thinking about how to handle that...
> add a total label to the staff roles table

- src/components/central-program/staff-roles-table.js
- src/components/central-programs-table.js
- src/components/table-utilities.js
You can now click on the program name of the first search result. 
Although, first row is removed (_Total ...._).
> Get rid of total row formatting when searching

- src/components/header.js
- src/components/language-picker.js
- src/components/new-feature.js
- src/pages/central-programs.js
- src/pages/whats-new.js
- src/translations/en.json
- src/translations/es.json
* Add **What's New** to the navigation
* Manage Navigation translations and order in Contentful (translations were in JSON files from an early experiment)
* Prettier reformatted some files I touched
Also added some new feature content / updates in Contentful that should be included when we build.
> Navigation Update / What's New Update

- data/central-programs-overview.json
- data/central-programs-resources.json
- data/central-programs-sankey.json
- data/central-programs.json
- data/sankey-restricted.json
- data/sankey.json
- gatsby-config.js
- scripts/testing/page-paths.json
- src/components/central-program.js
- src/components/central-program/program-data-overview-table.js
- src/components/pie-chart.scss
Also hiding previous year comparisons when they are not available
> Update Data for 2020-21

- src/components/central-program.js
- src/components/multi-year-chart.js
adding some code quality fixes I forgot to push before merging
> multi-year PR fixes

- data/central-programs-sankey-restricted.json
- data/central-programs-sankey.json
- scripts/build_json.py
- src/components/central-program.js
- src/components/central-program/central-program.scss
- src/components/error-boundary.js
- src/components/line-chart.js
- src/components/sankey-chart.js
- src/components/sankey-chart.scss
- src/pages/central-programs.js
> Central Program - Sankey

- package-lock.json
- package.json
- src/pages/contact.js
A few months ago, I started getting a ton of spam. The form submission service supports recaptcha integration, so want to try it.
> Using reCaptcha On Contact form
